### ISSUE TITLE
Build Detector Improvements

### ISSUE THREAD

**Issue by underscoreglider** [MindlessReader/Empires#16]
- Show building requirements above the bats ( building detectors )

- Show build progress above building detectors ( i.e. port: 150/200 blocks)

- Show building requirements in book

**Comment by MindlessReader** [comment]
Scores of detectors are now displayed in the latest working test of Empires. These changes will go live in the v0.2.0-beta update, currently scheduled for March 9, 2019 (3/9/19) at 1 pm PST.
